
name: Build Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Extract previous commit hash
        run:  echo "PREVIOUS_COMMIT_HASH=$(git rev-parse HEAD~1)" >> $GITHUB_ENV
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build & Publish Frontend Image
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: type=registry,ref=${{ secrets.REGISTRY_URL }}/${{ secrets.FRONT_DOCKER_REPOSITORY }}:${{ env.PREVIOUS_COMMIT_HASH }}
          cache-to: type=inline
          target: frontend-builder
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.FRONT_DOCKER_REPOSITORY }}:${{ env.BRANCH_NAME }}
            ${{ secrets.REGISTRY_URL }}/${{ secrets.FRONT_DOCKER_REPOSITORY }}:${{ github.sha }}
      - name: Build & Publish Backend Image
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: |
              type=registry,ref=${{ secrets.REGISTRY_URL }}/${{ secrets.DOCKER_REPOSITORY }}:${{ env.BRANCH_NAME }}
              type=registry,ref=${{ secrets.REGISTRY_URL }}/${{ secrets.FRONT_DOCKER_REPOSITORY }}:${{ env.PREVIOUS_COMMIT_HASH }}
          cache-to: type=inline
          tags: |
            ${{ secrets.REGISTRY_URL }}/${{ secrets.DOCKER_REPOSITORY }}:${{ env.BRANCH_NAME }}
            ${{ secrets.REGISTRY_URL }}/${{ secrets.DOCKER_REPOSITORY }}:${{ github.sha }}
